env: prod
component: payment
params: "CART_HOST:prod.payment.cart_host,CART_PORT:prod.payment.cart_port,USER_HOST:prod.payment.user_host,USER_PORT:prod.payment.user_port,AMQP_HOST:prod.payment.ampq_host,AMQP_USER:prod.payment.ampq_user,AMQP_PASS:prod.payment.ampq_pass"

